// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Inventory struct {
	ID           int32              `json:"id"`
	TenantID     int32              `json:"tenant_id"`
	LocationID   int32              `json:"location_id"`
	ChickenCount *int32             `json:"chicken_count"`
	Feed         *int32             `json:"feed"`
	LoadDate     pgtype.Date        `json:"load_date"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Location struct {
	ID            int32              `json:"id"`
	TenantID      int32              `json:"tenant_id"`
	Location      string             `json:"location"`
	ZipCode       *string            `json:"zip_code"`
	Latitude      pgtype.Numeric     `json:"latitude"`
	Longitude     pgtype.Numeric     `json:"longitude"`
	ContactPerson *string            `json:"contact_person"`
	Phone         *string            `json:"phone"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Role struct {
	ID          int32    `json:"id"`
	Name        string   `json:"name"`
	Permissions []string `json:"permissions"`
}

type SuperAdmin struct {
	ID           int32              `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Tenant struct {
	ID         int32              `json:"id"`
	Name       string             `json:"name"`
	LicenseKey string             `json:"license_key"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           int32              `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	TenantID     *int32             `json:"tenant_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
